This script follows the capstone stage two black box optimisation challenge, this is the first attempt for week 1

In [7]:
import numpy as np
import matplotlib.pyplot as plt
import os 
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF

In [8]:
# UCB function 
def acquisition_UCB(beta, mean, stddev, candidates):

    ucb = mean + beta * stddev # compute UCB 
    best_index = np.argmax(ucb) # find the argument x of a(x) that maximises 

    # use index to find best candidate function

    return np.round(candidates[best_index],6)

# implement GPR with a RBF kernel 
def GPR_with_RBF_kernel(rbf_lengthscale,
                        noise_assumption,
                        ins,outs,
                        sample_size,
                        in_cols):
    kernel = RBF(length_scale=rbf_lengthscale, length_scale_bounds='fixed')
    model = GaussianProcessRegressor(kernel = kernel, alpha=noise_assumption)

    # normalise all dimensions 
    
   
    #fit data to GPR model 
    model.fit(ins,outs)



    # generate possible coordinate samples for acquisition function


    rng = np.random.default_rng(seed=42)

    sample_ins = rng.random((sample_size, in_cols))

    # above sample assumes the coords are between [0,1)

    post_mean, post_std = model.predict(sample_ins ,return_std=True)

    return post_mean, post_std, sample_ins

Import the data for function 1, fortunately the inputs are between 0,1 for all functions, 
next week we should implement some rigorous scaling for both the ins and outs, also need to check direction of results are we appropriately maximising in each case or is there a negative sign needed somewhere.


In [10]:
#f1 cell 
print(os.getcwd())
ins=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_1/initial_inputs.npy")
outs=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_1/initial_outputs.npy")
print("shape outputs",np.shape(outs))
print("shape inputs",np.shape(ins))
print(np.min(ins),np.max(ins))
print(np.min(outs),np.max(outs))
print(outs)
#Parameters of the problem. Feel free to change them and play around with
real_noise_std = 1e-10 #Real noise needs to be positive for code to work, instead of zero set 1e-10
noise_assumption = 1e-10 #Noise assumption, a hyperparameter
rbf_lengthscale = 0.5 #Length scale parameter
sample_size=10000
in_cols=2
Beta=5

post_mean, post_std,sample_ins=GPR_with_RBF_kernel(rbf_lengthscale,
                        noise_assumption,
                        ins,outs,
                        sample_size,
                        in_cols)

x_next=acquisition_UCB(Beta,post_mean, post_std,sample_ins)
print(x_next)


# 2-D input to 1-D out is hard to visualise clearly so wont bother


/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data
shape outputs (10,)
shape inputs (10, 2)
0.07872277794971883 0.8838898288181171
-0.0036060626443634764 7.710875114502849e-16
[ 1.32267704e-079  1.03307824e-046  7.71087511e-016  3.34177101e-124
 -3.60606264e-003 -2.15924904e-054 -2.08909327e-091  2.53500115e-040
  3.60677119e-081  6.22985647e-048]
[0.00445  0.994344]


In [4]:
#f2 cell 
print(os.getcwd())
ins=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_2/initial_inputs.npy")
outs=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_2/initial_outputs.npy")
print("shape outputs",np.shape(outs))
print("shape inputs",np.shape(ins))
print(np.min(ins),np.max(ins))
print(np.min(outs),np.max(outs))
print(outs)
#Parameters of the problem. Feel free to change them and play around with
real_noise_std = 1e-10 #Real noise needs to be positive for code to work, instead of zero set 1e-10
noise_assumption = 1e-10 #Noise assumption, a hyperparameter
rbf_lengthscale = 0.5 #Length scale parameter
sample_size=10000
in_cols=2
Beta=5

post_mean, post_std,sample_ins=GPR_with_RBF_kernel(rbf_lengthscale,
                        noise_assumption,
                        ins,outs,
                        sample_size,
                        in_cols)

x_next=acquisition_UCB(Beta,post_mean, post_std,sample_ins)
print(x_next)


# 2-D input to 1-D out is hard to visualise clearly so wont bother


/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data
shape outputs (10,)
shape inputs (10, 2)
0.028697719822277867 0.9265641975455574
-0.06562362443733738 0.6112052157614438
[ 0.53899612  0.42058624 -0.06562362  0.29399291  0.21496451  0.02310555
  0.24461934  0.03874902 -0.01385762  0.61120522]
[0.00445  0.994344]


In [15]:
#f3 cell 
print(os.getcwd())
ins=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_3/initial_inputs.npy")
outs=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_3/initial_outputs.npy")
print("shape outputs",np.shape(outs))
print(outs)
print("shape inputs",np.shape(ins))
print(np.min(ins),np.max(ins))
print(np.min(outs),np.max(outs))
#Parameters of the problem. Feel free to change them and play around with
real_noise_std = 1e-10 #Real noise needs to be positive for code to work, instead of zero set 1e-10
noise_assumption = 1e-10 #Noise assumption, a hyperparameter
rbf_lengthscale = 0.5 #Length scale parameter
sample_size=10000
in_cols=3
Beta=5

post_mean, post_std,sample_ins=GPR_with_RBF_kernel(rbf_lengthscale,
                        noise_assumption,
                        ins,outs,
                        sample_size,
                        in_cols)

x_next=acquisition_UCB(Beta,post_mean, post_std,sample_ins)
print(x_next)


/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data
shape outputs (15,)
[-0.1121222  -0.08796286 -0.11141465 -0.03483531 -0.04800758 -0.11062091
 -0.39892551 -0.11386851 -0.13146061 -0.09418956 -0.04694741 -0.10596504
 -0.11804826 -0.03637783 -0.05675837]
shape inputs (15, 3)
0.046808949722497384 0.990881866558951
-0.3989255131463011 -0.034835313350078584
[0.9757   0.018176 0.952237]


In [5]:
#f4 cell 
print(os.getcwd())
ins=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_4/initial_inputs.npy")
outs=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_4/initial_outputs.npy")
print("shape outputs",np.shape(outs))
print("shape inputs",np.shape(ins))
print(np.min(ins),np.max(ins))
print(np.min(outs),np.max(outs))
print(outs)
#Parameters of the problem. Feel free to change them and play around with
real_noise_std = 1e-10 #Real noise needs to be positive for code to work, instead of zero set 1e-10
noise_assumption = 1e-10 #Noise assumption, a hyperparameter
rbf_lengthscale = 0.5 #Length scale parameter
sample_size=10000
in_cols=4
Beta=5

post_mean, post_std,sample_ins=GPR_with_RBF_kernel(rbf_lengthscale,
                        noise_assumption,
                        ins,outs,
                        sample_size,
                        in_cols)

x_next=acquisition_UCB(Beta,post_mean, post_std,sample_ins)
print(x_next)

/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data
shape outputs (30,)
shape inputs (30, 4)
0.006250400244917853 0.9994825612275692
-32.625660215962455 -4.025542281908162
[-22.10828779 -14.60139663 -11.69993246 -16.05376511 -10.06963343
 -15.48708254 -12.68168498 -16.02639977 -17.04923465 -12.74176599
 -27.31639636 -13.52764887 -16.6791152  -16.50715856 -17.81799934
 -26.56182083 -12.75832422 -19.44155762 -28.90327367 -13.70274694
 -29.4270914  -11.56574199 -26.85778644  -7.96677535  -6.70208925
 -32.62566022 -19.98949793  -4.02554228 -13.12278233 -23.1394284 ]
[0.508167 0.489502 0.333094 0.431327]


In [17]:
#f5 cell 
print(os.getcwd())
ins=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_5/initial_inputs.npy")
outs=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_5/initial_outputs.npy")
print("shape outputs",np.shape(outs))
print("shape inputs",np.shape(ins))
print(np.min(ins),np.max(ins))
print(np.min(outs),np.max(outs))
print(outs)
#Parameters of the problem. Feel free to change them and play around with
real_noise_std = 1e-10 #Real noise needs to be positive for code to work, instead of zero set 1e-10
noise_assumption = 1e-10 #Noise assumption, a hyperparameter
rbf_lengthscale = 0.5 #Length scale parameter
sample_size=10000
in_cols=4
Beta=5

post_mean, post_std,sample_ins=GPR_with_RBF_kernel(rbf_lengthscale,
                        noise_assumption,
                        ins,outs,
                        sample_size,
                        in_cols)

x_next=acquisition_UCB(Beta,post_mean, post_std,sample_ins)
print(x_next)

/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data
shape outputs (20,)
shape inputs (20, 4)
0.03819337135150802 0.957643898670113
0.1129397953712203 1088.8596181962705
[6.44434399e+01 1.83013796e+01 1.12939795e-01 4.21089813e+00
 2.58370525e+02 7.84343889e+01 5.75715369e+01 1.09571876e+02
 8.84799176e+00 2.33223610e+02 2.44230883e+01 6.44201468e+01
 6.34767158e+01 7.97291299e+01 3.55806818e+02 1.08885962e+03
 2.88667516e+01 4.51815703e+01 4.31612757e+02 9.97233189e+00]
[0.377511 0.871594 0.988652 0.967795]


In [6]:
#f6 cell 
print(os.getcwd())
ins=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_6/initial_inputs.npy")
outs=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_6/initial_outputs.npy")
print("shape outputs",np.shape(outs))
print("shape inputs",np.shape(ins))
print(np.min(ins),np.max(ins))
print(np.min(outs),np.max(outs))
print(outs)
#Parameters of the problem. Feel free to change them and play around with
real_noise_std = 1e-10 #Real noise needs to be positive for code to work, instead of zero set 1e-10
noise_assumption = 1e-10 #Noise assumption, a hyperparameter
rbf_lengthscale = 0.5 #Length scale parameter
sample_size=10000
in_cols=5
Beta=5

post_mean, post_std,sample_ins=GPR_with_RBF_kernel(rbf_lengthscale,
                        noise_assumption,
                        ins,outs,
                        sample_size,
                        in_cols)

x_next=acquisition_UCB(Beta,post_mean, post_std,sample_ins)
print(x_next)

/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data
shape outputs (20,)
shape inputs (20, 5)
0.004911495864404647 0.9788057635601997
-2.5711696316081234 -0.7142649478202404
[-0.71426495 -1.20995524 -1.67219994 -1.53605771 -0.82923655 -1.24704893
 -1.23378638 -1.69434344 -2.57116963 -1.30911635 -1.14478485 -1.91267714
 -1.62283895 -1.35668211 -2.0184254  -1.70255784 -1.29424696 -0.93575656
 -2.15576776 -1.74688209]
[0.839227 0.059535 0.938613 0.042403 0.981669]


In [19]:
#f7 cell 
print(os.getcwd())
ins=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_7/initial_inputs.npy")
outs=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_7/initial_outputs.npy")
print("shape outputs",np.shape(outs))
print("shape inputs",np.shape(ins))
print(np.min(ins),np.max(ins))
print(np.min(outs),np.max(outs))
print(outs)
#Parameters of the problem. Feel free to change them and play around with
real_noise_std = 1e-10 #Real noise needs to be positive for code to work, instead of zero set 1e-10
noise_assumption = 1e-10 #Noise assumption, a hyperparameter
rbf_lengthscale = 0.5 #Length scale parameter
sample_size=10000
in_cols=6
Beta=5

post_mean, post_std,sample_ins=GPR_with_RBF_kernel(rbf_lengthscale,
                        noise_assumption,
                        ins,outs,
                        sample_size,
                        in_cols)

x_next=acquisition_UCB(Beta,post_mean, post_std,sample_ins)
print(x_next)

/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data
shape outputs (30,)
shape inputs (30, 6)
0.0036345648296357558 0.9986546964586872
0.0027014650245082332 1.3649683044991994
[0.6044327  0.56275307 0.00750324 0.0614243  0.2730468  0.08374657
 1.3649683  0.09264495 0.0178696  0.03356494 0.0735163  0.2063097
 0.00882563 0.26840032 0.61152553 0.01479818 0.27489251 0.06676325
 0.04211835 0.00270147 0.01820907 0.00701603 0.10050661 0.47539552
 0.67514163 0.51645722 0.00377748 0.00313433 0.02134252 0.09541116]
[0.014159 0.967762 0.632863 0.010833 0.49052  0.157537]


In [20]:
#f8 cell 
print(os.getcwd())
ins=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_8/initial_inputs.npy")
outs=np.load("/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data/function_8/initial_outputs.npy")
print("shape outputs",np.shape(outs))
print("shape inputs",np.shape(ins))
print(np.min(ins),np.max(ins))
print(np.min(outs),np.max(outs))
print(outs)
#Parameters of the problem. Feel free to change them and play around with
real_noise_std = 1e-10 #Real noise needs to be positive for code to work, instead of zero set 1e-10
noise_assumption = 1e-10 #Noise assumption, a hyperparameter
rbf_lengthscale = 0.5 #Length scale parameter
sample_size=10000
in_cols=8
Beta=5

post_mean, post_std,sample_ins=GPR_with_RBF_kernel(rbf_lengthscale,
                        noise_assumption,
                        ins,outs,
                        sample_size,
                        in_cols)

x_next=acquisition_UCB(Beta,post_mean, post_std,sample_ins)
print(x_next)

/Users/luke_dev/Documents/ML_AI_imperial_course_codes/capstone_stage_2/initial_data
shape outputs (40,)
shape inputs (40, 8)
0.0034194994840646142 0.9988854968558359
5.5921933895401965 9.598482002566342
[7.3987211  7.00522736 8.45948162 8.28400781 8.60611679 8.54174792
 7.32743458 7.29987205 7.95787474 5.59219339 7.85454099 6.79198578
 8.97655402 7.3790829  9.598482   8.15998319 7.13162397 6.76796253
 7.43374407 9.01307515 7.31089382 5.84106731 9.14163949 8.81755844
 6.45194313 8.83074505 9.34427428 6.88784639 8.04221254 7.69236805
 7.92375877 8.42175924 8.2780624  7.11345716 6.40258841 8.47293632
 7.97768459 7.46087219 7.43659353 9.18300525]
[0.360178 0.477812 0.322229 0.423164 0.580747 0.34964  0.464133 0.496224]
